FROM alpine:latest

ARG GITCOMMIT
ENV GITCOMMIT=${GITCOMMIT:-unknown}
ARG GITBRANCH
ENV GITBRANCH=${GITBRANCH:-unknown}
ENV REV=1
RUN echo GITCOMMIT=$GITCOMMIT && \
    echo GITBRANCH=$GITBRANCH && \
    echo REV=$REV

CMD env | grep GIT
