name: cd
on:
  workflow_run:
    workflows:
      - ci
    types: 
      - completed
env:
  QUAY_REPO: quay.io/packet/mmlb-test-gha-pushes
jobs:
  upload:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

        # from https://securitylab.github.com/research/github-actions-preventing-pwn-requests
        # until https://github.com/actions/download-artifact/issues/60 is closed
      - name: Download artifact
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "image"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/image.zip', Buffer.from(download.data));

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}

      - name: Load Image Into Docker
        run: |
          unzip image.zip
          docker load <image.tar

      - name: ReTag and Push
        run: |
          sha=${{ github.event.workflow_run.head_sha }}
          sha=${sha::8}
          tags=()
          if [[ ${{ github.event.workflow_run.event}} == "pull_request" ]]; then
              QUAY_REPO+=-pr
              tags+=(${QUAY_REPO}:pr${{ github.event.workflow_run.pull }})
              tags+=(${QUAY_REPO}:pr${{ github.event.workflow_run.pull }}-sha${sha})
          else
              tags+=(${QUAY_REPO}:sha${sha})
              tags+=(${QUAY_REPO}:${{ github.event.workflow_run.head_branch }}-sha${sha})
              if [[ ${{ github.event.workflow_run.head_branch }} == 'main' ]]; then
                  tags+=(${QUAY_REPO}:latest)
              fi
          fi
          iid=$(docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' | awk "/ci-image-build:sha-${GITHUB_SHA::8}/ {print $2}")
          set -x
          for tag in "${tags[@]}"; do
              docker tag "$iid" "$tag"
              docker push "$tag"
          done
          set +x
