name: cd
on:
  workflow_run:
    workflows:
      - ci
    types: 
      - completed

jobs:
  upload:
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

        # from https://securitylab.github.com/research/github-actions-preventing-pwn-requests
        # until https://github.com/actions/download-artifact/issues/60 is closed
      - name: Download artifact
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "image"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/image.zip', Buffer.from(download.data));

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}

      - name: Load Image Into Docker
        run: |
          unzip image.zip
          ls
          docker images
          docker load <image.tar
          docker images
      - name: Push to Quay
        run:  docker push $(docker images | awk '/quay.io/ {print $1 ":" $2}')
