name: ci
on:
  pull_request:
  push:
env:
  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          tags: ci-image-build:sha-${{github.sha}}
          cache-from: type=registry,ref=${QUAY_REPO}:latest
          cache-to: type=inline
          platforms: ${{env.platforms}}
          build-args: |
            GITCOMMIT=${{github.sha}}
            GITBRANCH=${{github.ref}}

      - name: Export Images
        run: |
          mkdir images
          set -x
          for platform in ${platforms}; do
            tag=sha-${{github.sha}}-${platform//-}
            docker buildx build --tag "ci-image-build:$tag" --platform=$platform --output type=docker,dest=images/$tag .
          done

      - name: Upload Image As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: images
