name: ci
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ci-image-build:sha-${{github.sha}}
          cache-from: type=registry,ref=${QUAY_REPO}:latest
          cache-to: type=inline
          build-args: |
            GITCOMMIT=${{github.sha}}
            GITBRANCH=${{github.ref}}

      - name: Save Image
        run: docker save ci-image-build:sha-${{github.sha}} >image.tar

      - name: Upload Image As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: image.tar

      - name: Image digest
        run: echo ${{steps.build-image.outputs.digest}}
