name: push-pr-images
on:
  workflow_run:
    workflows:
      - ci
    types: 
      - completed
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - run: env | sort
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
